import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home({results}: {results: any}) {

  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Navbar */}
      <Navbar />

      {/* Results */}
      <Results results={results}/>
    </div>
  )
}

export async function getServerSideProps(ctx: any) {
  const genre = ctx.query.genre as (keyof typeof requests);

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`);

  const results = await request.json();
  return {
    props: {
      results: results.results
    }
  }
}